name: Bug Report
description: Report a bug in our E-commerce Analytics Hub API Gateway or related services.
title: '[API Bug]: '
labels: ['api', 'bug', 'backend']
assignees:
  - backendteam

body:
  - type: markdown
    attributes:
      value: |
        🚀 Thank you for taking the time to fill out this bug report for our E-commerce Analytics Hub API Gateway. Please fill out the sections below to the best of your ability.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the issue with the backend service, including what you expected to happen instead.
      placeholder: Please describe the issue in detail, including expected and actual outcomes.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Detail the steps taken to encounter the issue.
      placeholder: 1. Make a request to endpoint '...' with payload '...' 2. Observe the unexpected response
    validations:
      required: true

  - type: input
    id: api-version
    attributes:
      label: API Version
      description: Which version of the API are you using?
      placeholder: e.g., v1
    validations:
      required: true

  - type: dropdown
    id: affected-service
    attributes:
      label: Affected Service
      description: Which service or component is affected?
      options:
        - API Gateway (Core)
        - Products API
        - Categories API
        - Redis Management
        - Database (PostgreSQL)
        - Documentation (Swagger)
        - Docker/Infrastructure
        - Other
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Where did this bug occur?
      placeholder: e.g., Development (Docker), Production, Local
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any additional information (e.g., Docker logs, Redis connection status, database errors, etc.) that might help in diagnosing the issue.
      placeholder: Include Docker logs, error messages, request/response examples, or any other details that might be helpful.
    validations:
      required: false

  - type: checkboxes
    id: reproduction
    attributes:
      label: Reproduction
      description: Can you reproduce this issue?
      options:
        - label: Yes, consistently
        - label: Yes, sometimes
        - label: No, it was a one-time occurrence
        - label: Not sure
